# ==============================================================
# = Spring docker compose
# ==============================================================
spring.docker.compose.enabled=true

# ==============================================================
# = Liquibase
# ==============================================================
spring.liquibase.contexts=local

# ==============================================================
# = Spring Datasource
# ==============================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/inventarbuddy
spring.datasource.username=dev
spring.datasource.password=pass
