# ==============================================================
# = Spring Vault
# ==============================================================
spring.config.import= "optional:vault://services/_shared/${spring.profiles.active},vault://services/customer-data-middleware/${spring.profiles.active}"