# ==============================================================
# = Spring docker compose
# ==============================================================
spring.docker.compose.enabled=true
spring.docker.compose.profiles.active=local

# ==============================================================
# = Spring JPA
# ==============================================================
spring.jpa.show-sql=true

# ==============================================================
# = Liquibase
# ==============================================================
spring.liquibase.contexts=local

# ==============================================================
# = Spring Datasource
# ==============================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/inventarbuddy
spring.datasource.username=dev
spring.datasource.password=pass

# ==============================================================
# = Spring Vault (Local Dev Mode)
# ==============================================================
spring.cloud.vault.enabled= true
spring.cloud.vault.host= localhost
spring.cloud.vault.port= 8200
spring.cloud.vault.scheme= http
spring.cloud.vault.authentication= TOKEN
spring.cloud.vault.token= dev-root-token
spring.cloud.vault.fail-fast= true
spring.cloud.vault.kv.enabled= true
spring.cloud.vault.kv.backend= inventarbuddy
spring.cloud.vault.kv.default-context= ""
spring.cloud.vault.kv.profiles= local

# ==============================================================
# = OAuth2 Resource Server
# ==============================================================
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/inventarbuddy
