# ==============================================================
# = Server Configuration
# ==============================================================
server.port=${port:8080}
server.tomcat.remoteip.remote-ip-header=X-Forwarded-For
server.tomcat.remoteip.protocol-header=X-Forwarded-Proto

# ==============================================================
# = Spring Basics
# ==============================================================
spring.application.name=@project.name@
spring.profiles.active=@spring.profiles.active@
spring.threads.virtual.enabled=true
spring.mvc.servlet.path=/inventarbuddy

# ==============================================================
# = Spring Datasource
# ==============================================================
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.tomcat.test-while-idle=true
spring.datasource.tomcat.validation-query=SELECT 1
spring.datasource.hikari.max-lifetime=30001

# ==============================================================
# = Spring JPA
# ==============================================================
spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.hibernate.naming.physical-strategy=de.toxic2302.inventarbuddy.config.NamingStrategy
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==============================================================
# = Liquibase
# ==============================================================
spring.liquibase.change-log=classpath:db/db.changelog-master.xml
spring.liquibase.default-schema=inventarbuddy

# ==============================================================
# = Spring docker compose
# ==============================================================
spring.docker.compose.enabled=false

# ==============================================================
# = Spring Vault
# ==============================================================
spring.cloud.vault.enabled= true
spring.cloud.vault.host= ${VAULT_HOST:localhost}
spring.cloud.vault.port= ${VAULT_PORT:8200}
spring.cloud.vault.scheme= ${VAULT_SCHEME:http}
spring.cloud.vault.authentication= APPROLE
spring.cloud.vault.app-role.role-id= ${VAULT_ROLE_ID}
spring.cloud.vault.app-role.secret-id= ${VAULT_SECRET_ID}
spring.cloud.vault.connection-timeout= 5000
spring.cloud.vault.read-timeout= 15000
spring.cloud.vault.fail-fast= true
spring.cloud.vault.kv.enabled= true
spring.cloud.vault.kv.backend= customer-data-middleware
spring.cloud.vault.kv.default-context= ""
spring.cloud.vault.kv.profiles= @spring.profiles.active@

# ==============================================================
# = Actuator Management Endpoints
# ==============================================================
management.endpoints.access.default=none
management.endpoints.web.exposure.include=health
management.endpoint.health.access=read_only
management.endpoint.health.show-details=never
management.endpoint.health.show-components=never
management.endpoint.health.probes.enabled=true
management.endpoint.info.access=none
management.endpoint.metrics.access=none
management.health.readinessstate.enabled=true
management.health.livenessstate.enabled=true
